"use client"
import { Provider } from 'react-redux'
import { Inter } from 'next/font/google'

import './globals.css'
import store from './store'
import Link from "next/link"

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className='flex justify-around mx-10 my-3 p-4 rounded-lg border border-orange-200 border-8 '>
      <Link href="/" className='hover:text-orange-300 active:text-orange-400'> Home </Link>
      <Link href="/memes"  className="hover:text-orange-300 active:text-orange-400" > Create Meme! </Link>
      </nav>
      <Provider store={store}>
        {children}
      </Provider>
        
        
        </body>
    </html>
  )
}
